// Code generated by MockGen. DO NOT EDIT.
// Source: ./provider.go
//
// Generated by this command:
//
//	mockgen -source=./provider.go -destination=./mock_provider.go -package=gothought
//

// Package gothought is a generated GoMock package.
package gothought

import (
	context "context"
	reflect "reflect"

	tool "github.com/gobenpark/gothought/tool"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockProvider) Generate(ctx context.Context, tools map[string]tool.Tool, messages []Message) (*Message, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, tools, messages)
	ret0, _ := ret[0].(*Message)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Generate indicates an expected call of Generate.
func (mr *MockProviderMockRecorder) Generate(ctx, tools, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockProvider)(nil).Generate), ctx, tools, messages)
}

// MockStreamingCapable is a mock of StreamingCapable interface.
type MockStreamingCapable struct {
	ctrl     *gomock.Controller
	recorder *MockStreamingCapableMockRecorder
	isgomock struct{}
}

// MockStreamingCapableMockRecorder is the mock recorder for MockStreamingCapable.
type MockStreamingCapableMockRecorder struct {
	mock *MockStreamingCapable
}

// NewMockStreamingCapable creates a new mock instance.
func NewMockStreamingCapable(ctrl *gomock.Controller) *MockStreamingCapable {
	mock := &MockStreamingCapable{ctrl: ctrl}
	mock.recorder = &MockStreamingCapableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamingCapable) EXPECT() *MockStreamingCapableMockRecorder {
	return m.recorder
}

// GenerateStreaming mocks base method.
func (m *MockStreamingCapable) GenerateStreaming(ctx context.Context, tools map[string]tool.Tool, messages []Message, callback func(Message) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateStreaming", ctx, tools, messages, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateStreaming indicates an expected call of GenerateStreaming.
func (mr *MockStreamingCapableMockRecorder) GenerateStreaming(ctx, tools, messages, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStreaming", reflect.TypeOf((*MockStreamingCapable)(nil).GenerateStreaming), ctx, tools, messages, callback)
}
